"""empty message

Revision ID: 42ef4a834d23
Revises: 39c1873bb19b
Create Date: 2016-04-10 23:00:26.630540

"""

# revision identifiers, used by Alembic.
revision = '42ef4a834d23'
down_revision = '39c1873bb19b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballot', sa.Column('end_timestamp', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballot', 'end_timestamp')
    ### end Alembic commands ###
