"""empty message

Revision ID: 4517f9cbe1f9
Revises: 42ef4a834d23
Create Date: 2016-04-13 22:34:37.727821

"""

# revision identifiers, used by Alembic.
revision = '4517f9cbe1f9'
down_revision = '42ef4a834d23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'ballot_option_ballot_id_fkey', 'ballot_option', type_='foreignkey')
    op.create_foreign_key(None, 'ballot_option', 'ballot', ['ballot_id'], ['id'], ondelete='cascade')
    op.drop_constraint(u'ballot_vote_ballot_option_fkey', 'ballot_vote', type_='foreignkey')
    op.create_foreign_key(None, 'ballot_vote', 'ballot_option', ['ballot_option'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ballot_vote', type_='foreignkey')
    op.create_foreign_key(u'ballot_vote_ballot_option_fkey', 'ballot_vote', 'ballot_option', ['ballot_option'], ['id'])
    op.drop_constraint(None, 'ballot_option', type_='foreignkey')
    op.create_foreign_key(u'ballot_option_ballot_id_fkey', 'ballot_option', 'ballot', ['ballot_id'], ['id'])
    ### end Alembic commands ###
