"""empty message

Revision ID: 494351630f57
Revises: 4517f9cbe1f9
Create Date: 2016-04-17 23:18:38.948883

"""

# revision identifiers, used by Alembic.
revision = '494351630f57'
down_revision = '4517f9cbe1f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballot_option', sa.Column('is_write_in', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballot_option', 'is_write_in')
    ### end Alembic commands ###
